import { atom } from "recoil";

// 검색창 키워드
export const searchKeywordState = atom({
  key: "SearchKeyword",
  default: "",
});

// 검색창 해시태그 (쉼표로 join된 문자열)
export const searchStringHashTagsState = atom({
  key: "SearchHashTags",
  default: "",
});

// 검색창 검색 결과
// 해시태그 검색 결과
export const hashTagsSearchResultState = atom({
  key: "HashTagsSearchResult",
  default: [],
});

// 사용자 이름 검색 결과
export const creatorSearchResultState = atom({
  key: "CreatorSearchResult",
  default: [],
});

// 방제 검색 결과
export const titleSearchResultState = atom({
  key: "TitleSearchResult",
  default: [],
});

// SearchRoom Page에서 사용할 더미데이터
export const dummyDataState = atom({
  key: "DummyData",
  default: [[
    // 첫 데이터, Page 0
    {},
    {
      "room_id": 14,
      "room_name": "13번",
      "room_creater_name": "13작성자",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#13,#213",
      "room_watch_cnt": 13,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://pbs.twimg.com/profile_images/1374979417915547648/vKspl9Et_400x400.jpg",
      "room_category": "일상"
    },
    {
      "room_id": 127,
      "room_name": "감자튀김 vs 고구마튀김 님들의 선택은?",
      "room_creater_name": "감튀파",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#감튀,#고튀,#튀김",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 127,
      "room_name": "감자튀김 vs 고구마튀김 님들의 선택은?",
      "room_creater_name": "감튀파",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#감튀,#고튀,#튀김",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 127,
      "room_name": "마지막 토론방",
      "room_creater_name": "마지막",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#page0,#last,#content",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 14,
      "room_name": "13번",
      "room_creater_name": "13작성자",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#13,#213",
      "room_watch_cnt": 13,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://pbs.twimg.com/profile_images/1374979417915547648/vKspl9Et_400x400.jpg",
      "room_category": "일상"
    },
    {
      "room_id": 127,
      "room_name": "감자튀김 vs 고구마튀김 님들의 선택은?",
      "room_creater_name": "감튀파",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#감튀,#고튀,#튀김",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 127,
      "room_name": "감자튀김 vs 고구마튀김 님들의 선택은?",
      "room_creater_name": "감튀파",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#감튀,#고튀,#튀김",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 127,
      "room_name": "마지막 토론방",
      "room_creater_name": "마지막",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#page0,#last,#content",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 14,
      "room_name": "13번",
      "room_creater_name": "13작성자",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#13,#213",
      "room_watch_cnt": 13,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://pbs.twimg.com/profile_images/1374979417915547648/vKspl9Et_400x400.jpg",
      "room_category": "일상"
    },
    {
      "room_id": 127,
      "room_name": "감자튀김 vs 고구마튀김 님들의 선택은?",
      "room_creater_name": "감튀파",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#감튀,#고튀,#튀김",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 127,
      "room_name": "감자튀김 vs 고구마튀김 님들의 선택은?",
      "room_creater_name": "감튀파",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#감튀,#고튀,#튀김",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 127,
      "room_name": "마지막 토론방",
      "room_creater_name": "마지막",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#page0,#last,#content",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 14,
      "room_name": "13번",
      "room_creater_name": "13작성자",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#13,#213",
      "room_watch_cnt": 13,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://pbs.twimg.com/profile_images/1374979417915547648/vKspl9Et_400x400.jpg",
      "room_category": "일상"
    },
    {
      "room_id": 127,
      "room_name": "감자튀김 vs 고구마튀김 님들의 선택은?",
      "room_creater_name": "감튀파",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#감튀,#고튀,#튀김",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 127,
      "room_name": "감자튀김 vs 고구마튀김 님들의 선택은?",
      "room_creater_name": "감튀파",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#감튀,#고튀,#튀김",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 127,
      "room_name": "마지막 토론방",
      "room_creater_name": "마지막",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#page0,#last,#content",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    }
  ],
  // 추가 데이터, Page 1
  [
    {
      "room_id": 127,
      "room_name": "추가 토론방 1",
      "room_creater_name": "추가1",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#page1,#1",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 127,
      "room_name": "추가 토론방 2",
      "room_creater_name": "추가2",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#page1,#2",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 127,
      "room_name": "추가 토론방 3",
      "room_creater_name": "추가3",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#page1,#3",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    }
  ],
  // 추가 데이터, Page 2
  [
    {
      "room_id": 127,
      "room_name": "추가 토론방 1",
      "room_creater_name": "추가1",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#page1,#1",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 14,
      "room_name": "13번",
      "room_creater_name": "13작성자",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#13,#213",
      "room_watch_cnt": 13,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://pbs.twimg.com/profile_images/1374979417915547648/vKspl9Et_400x400.jpg",
      "room_category": "일상"
    },
    {
      "room_id": 127,
      "room_name": "감자튀김 vs 고구마튀김 님들의 선택은?",
      "room_creater_name": "감튀파",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#감튀,#고튀,#튀김",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 127,
      "room_name": "감자튀김 vs 고구마튀김 님들의 선택은?",
      "room_creater_name": "감튀파",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#감튀,#고튀,#튀김",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 127,
      "room_name": "마지막 토론방",
      "room_creater_name": "마지막",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#page0,#last,#content",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 14,
      "room_name": "13번",
      "room_creater_name": "13작성자",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#13,#213",
      "room_watch_cnt": 13,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://pbs.twimg.com/profile_images/1374979417915547648/vKspl9Et_400x400.jpg",
      "room_category": "일상"
    },
    {
      "room_id": 127,
      "room_name": "감자튀김 vs 고구마튀김 님들의 선택은?",
      "room_creater_name": "감튀파",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#감튀,#고튀,#튀김",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 127,
      "room_name": "감자튀김 vs 고구마튀김 님들의 선택은?",
      "room_creater_name": "감튀파",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#감튀,#고튀,#튀김",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 127,
      "room_name": "마지막 토론방",
      "room_creater_name": "마지막",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#page0,#last,#content",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 14,
      "room_name": "13번",
      "room_creater_name": "13작성자",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#13,#213",
      "room_watch_cnt": 13,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://pbs.twimg.com/profile_images/1374979417915547648/vKspl9Et_400x400.jpg",
      "room_category": "일상"
    },
    {
      "room_id": 127,
      "room_name": "감자튀김 vs 고구마튀김 님들의 선택은?",
      "room_creater_name": "감튀파",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#감튀,#고튀,#튀김",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 127,
      "room_name": "감자튀김 vs 고구마튀김 님들의 선택은?",
      "room_creater_name": "감튀파",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#감튀,#고튀,#튀김",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 127,
      "room_name": "마지막 토론방",
      "room_creater_name": "마지막",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#page0,#last,#content",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 14,
      "room_name": "13번",
      "room_creater_name": "13작성자",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#13,#213",
      "room_watch_cnt": 13,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://pbs.twimg.com/profile_images/1374979417915547648/vKspl9Et_400x400.jpg",
      "room_category": "일상"
    },
    {
      "room_id": 127,
      "room_name": "감자튀김 vs 고구마튀김 님들의 선택은?",
      "room_creater_name": "감튀파",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#감튀,#고튀,#튀김",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 127,
      "room_name": "감자튀김 vs 고구마튀김 님들의 선택은?",
      "room_creater_name": "감튀파",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#감튀,#고튀,#튀김",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 127,
      "room_name": "마지막 토론방",
      "room_creater_name": "마지막",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#page0,#last,#content",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 14,
      "room_name": "13번",
      "room_creater_name": "13작성자",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#13,#213",
      "room_watch_cnt": 13,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://pbs.twimg.com/profile_images/1374979417915547648/vKspl9Et_400x400.jpg",
      "room_category": "일상"
    },
    {
      "room_id": 127,
      "room_name": "감자튀김 vs 고구마튀김 님들의 선택은?",
      "room_creater_name": "감튀파",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#감튀,#고튀,#튀김",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 127,
      "room_name": "감자튀김 vs 고구마튀김 님들의 선택은?",
      "room_creater_name": "감튀파",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#감튀,#고튀,#튀김",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 127,
      "room_name": "마지막 토론방",
      "room_creater_name": "마지막",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#page0,#last,#content",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 127,
      "room_name": "추가 토론방 2",
      "room_creater_name": "추가2",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#page1,#2",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 127,
      "room_name": "추가 토론방 3",
      "room_creater_name": "추가3",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#page1,#3",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    }
  ],
  // 추가 데이터, Page 2
  [
    {
      "room_id": 127,
      "room_name": "추가 토론방 1",
      "room_creater_name": "추가1",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#page1,#1",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 127,
      "room_name": "추가 토론방 2",
      "room_creater_name": "추가2",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#page1,#2",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 127,
      "room_name": "추가 토론방 3",
      "room_creater_name": "추가3",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#page1,#3",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    }
  ],
  // 추가 데이터, Page 2
  [
    {
      "room_id": 127,
      "room_name": "추가 토론방 1",
      "room_creater_name": "추가1",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#page1,#1",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 127,
      "room_name": "추가 토론방 2",
      "room_creater_name": "추가2",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#page1,#2",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 127,
      "room_name": "추가 토론방 3",
      "room_creater_name": "추가3",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#page1,#3",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    }
  ],
  // 추가 데이터, Page 2
  [
    {
      "room_id": 127,
      "room_name": "추가 토론방 1",
      "room_creater_name": "추가1",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#page1,#1",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 127,
      "room_name": "추가 토론방 2",
      "room_creater_name": "추가2",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#page1,#2",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 127,
      "room_name": "추가 토론방 3",
      "room_creater_name": "추가3",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#page1,#3",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    }
  ],
  // 추가 데이터, Page 2
  [
    {
      "room_id": 127,
      "room_name": "추가 토론방 1",
      "room_creater_name": "추가1",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#page1,#1",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 127,
      "room_name": "추가 토론방 2",
      "room_creater_name": "추가2",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#page1,#2",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 127,
      "room_name": "추가 토론방 3",
      "room_creater_name": "추가3",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#page1,#3",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    }
  ],
  // 추가 데이터, Page 2
  [
    {
      "room_id": 127,
      "room_name": "추가 토론방 1",
      "room_creater_name": "추가1",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#page1,#1",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 127,
      "room_name": "추가 토론방 2",
      "room_creater_name": "추가2",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#page1,#2",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 127,
      "room_name": "추가 토론방 3",
      "room_creater_name": "추가3",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#page1,#3",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    }
  ],
  // 추가 데이터, Page 2
  [
    {
      "room_id": 127,
      "room_name": "추가 토론방 1",
      "room_creater_name": "추가1",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#page1,#1",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 127,
      "room_name": "추가 토론방 2",
      "room_creater_name": "추가2",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#page1,#2",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    },
    {
      "room_id": 127,
      "room_name": "추가 토론방 3",
      "room_creater_name": "추가3",
      "room_debate_type": "SHORT",
      "room_opinion_left": "leftopinon",
      "room_opinion_right": "rightopinion",
      "room_hashtags": "#page1,#3",
      "room_watch_cnt": 140,
      "room_phase": 2,
      "room_start_time": "2023-01-26T14:09:54.00494",
      "room_thumbnail_url": "https://picsum.photos/400/225",
      "room_category": "음식"
    }
  ]],
});